# Generated by Django 4.2.4 on 2023-08-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0002_alter_product_category_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Цвет"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Цена"
            ),
        ),
    ]
